//LOCALHOST
###get all recipes
GET http://localhost:8080/recipes

###create one new recipe
POST http://localhost:8080/recipes HTTP/1.1 
content-type: application/json

{
    "name":"Pap",
    "category":"South African",
    "email":"pap@test.com",
    "ingredients":[ "Boiling Water", "maize meal", "salt"],
    "prepTime":"5 minutes",
    "cookTime":"10 minutes",
    "servings":"6"
}

###
###delete recipe 
DELETE http://localhost:8080/recipes/62b66fdffc6f94efb2f41fdc HTTP/1.1

##